name: Cron job and manual run
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  build:
    deploy:
      name: test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build and push
          run: |
            docker build . --file Dockerfile --no-cache --tag test_container
            docker run test_container:latest